spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.MySQLDialect